/** AUTO-GENERATED by scripts/generate-affinities.mjs.
 *  Do NOT edit by hand — re-run the generator after any registry update.
 *
 *  These affinities are derived from each template's division + templateId
 *  keywords. The hand-authored entries in affinities.ts always take
 *  precedence (the scorer checks AFFINITIES first, then AUTO_AFFINITIES). */

import type { TemplateAffinities } from "./affinities.js";

export const AUTO_AFFINITIES: Record<string, TemplateAffinities> = {
  "ceo": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "chief-of-staff": {
    "industries": [],
    "stages": [
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "cmo": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "cro": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "cto": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "coo": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "cfo": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "cdo": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "cpo": {
    "industries": [],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "backend-architect": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "frontend-developer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "concierge-ops": {
    "industries": [
      "saas-b2b",
      "fintech",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "hubspot",
      "salesforce"
    ]
  },
  "product-manager": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "ux-researcher": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "trend-researcher": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "financial-analyst": {
    "industries": [
      "saas-b2b",
      "fintech"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "bookkeeper": {
    "industries": [
      "saas-b2b",
      "fintech"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "composio-integration": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "ai-data-remediation-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "autonomous-optimization-architect": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "cms-developer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "code-reviewer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "codebase-onboarding-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "database-optimizer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "email-intelligence-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "embedded-firmware-engineer": {
    "industries": [
      "saas-b2b",
      "open-source",
      "hardware"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "feishu-integration-developer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "filament-optimization-specialist": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "0_10k_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "git-workflow-master": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "incident-response-commander": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "minimal-change-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "mobile-app-builder": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "rapid-prototyper": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "security-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "senior-developer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "software-architect": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "solidity-smart-contract-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "github"
    ]
  },
  "sre": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "technical-writer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo",
      "community-led"
    ],
    "connectors": [
      "github"
    ]
  },
  "threat-detection-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "voice-ai-integration-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "wechat-mini-program-developer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "1m_5m_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": [
      "github"
    ]
  },
  "agentic-search-optimizer": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "ai-citation-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "app-store-optimizer": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "bilibili-content-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "book-co-author": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "carousel-growth-engine": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "china-ecommerce-operator": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "china-market-localization-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "cross-border-ecommerce": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "douyin-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "instagram-curator": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "kuaishou-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "livestream-commerce-coach": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "podcast-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "private-domain-operator": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "reddit-community-builder": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "short-video-editing-coach": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "social-media-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "tiktok-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "twitter-engager": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "video-optimization-specialist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "0_10k_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "wechat-official-account": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace",
      "fintech"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "weibo-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "xiaohongshu-specialist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "0_10k_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "zhihu-strategist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led",
      "community-led"
    ],
    "connectors": []
  },
  "account-strategist": {
    "industries": [
      "saas-b2b",
      "fintech",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "hubspot",
      "salesforce"
    ]
  },
  "deal-strategist": {
    "industries": [
      "saas-b2b",
      "fintech",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "hubspot",
      "salesforce"
    ]
  },
  "discovery-coach": {
    "industries": [
      "saas-b2b",
      "fintech",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "hubspot",
      "salesforce"
    ]
  },
  "outbound-strategist": {
    "industries": [
      "saas-b2b",
      "fintech",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "hubspot",
      "salesforce"
    ]
  },
  "pipeline-analyst": {
    "industries": [
      "saas-b2b",
      "fintech",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "hubspot",
      "salesforce"
    ]
  },
  "proposal-strategist": {
    "industries": [
      "saas-b2b",
      "fintech",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": [
      "hubspot",
      "salesforce"
    ]
  },
  "behavioral-nudge-engine": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "feedback-synthesizer": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "sprint-prioritizer": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "image-prompt-engineer": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led"
    ],
    "connectors": []
  },
  "inclusive-visuals-specialist": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "0_10k_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led"
    ],
    "connectors": []
  },
  "ui-designer": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led"
    ],
    "connectors": []
  },
  "ux-architect": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [
      "self-serve",
      "paid-led"
    ],
    "connectors": []
  },
  "visual-storyteller": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led"
    ],
    "connectors": []
  },
  "whimsy-injector": {
    "industries": [
      "saas-b2b",
      "saas-b2c",
      "ecommerce-dtc"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "paid-led"
    ],
    "connectors": []
  },
  "fpa-analyst": {
    "industries": [
      "saas-b2b",
      "fintech"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "investment-researcher": {
    "industries": [
      "saas-b2b",
      "fintech"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "tax-strategist": {
    "industries": [
      "saas-b2b",
      "fintech"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "executive-summary-generator": {
    "industries": [
      "saas-b2b",
      "marketplace",
      "ecommerce-dtc"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "finance-tracker": {
    "industries": [
      "saas-b2b",
      "marketplace",
      "ecommerce-dtc",
      "fintech"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "legal-compliance-checker": {
    "industries": [
      "saas-b2b",
      "marketplace",
      "ecommerce-dtc",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "responder": {
    "industries": [
      "saas-b2b",
      "marketplace",
      "ecommerce-dtc"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "self-serve",
      "assisted-demo"
    ],
    "connectors": []
  },
  "evidence-collector": {
    "industries": [
      "saas-b2b",
      "fintech",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "test-results-analyzer": {
    "industries": [
      "saas-b2b",
      "fintech",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "tool-evaluator": {
    "industries": [
      "saas-b2b",
      "fintech",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "500k_1m_arr",
      "1m_5m_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "assisted-demo",
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "auditor": {
    "industries": [
      "ecommerce-dtc",
      "saas-b2c",
      "marketplace",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "paid-led"
    ],
    "connectors": [
      "meta-ads-api",
      "google-ads-api"
    ]
  },
  "paid-social-strategist": {
    "industries": [
      "ecommerce-dtc",
      "saas-b2c",
      "marketplace",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "paid-led"
    ],
    "connectors": [
      "meta-ads-api",
      "google-ads-api"
    ]
  },
  "programmatic-buyer": {
    "industries": [
      "ecommerce-dtc",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "paid-led"
    ],
    "connectors": [
      "meta-ads-api",
      "google-ads-api"
    ]
  },
  "search-query-analyst": {
    "industries": [
      "ecommerce-dtc",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "paid-led"
    ],
    "connectors": [
      "meta-ads-api",
      "google-ads-api"
    ]
  },
  "tracking-specialist": {
    "industries": [
      "ecommerce-dtc",
      "saas-b2c",
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "0_10k_arr",
      "10k_100k_mrr"
    ],
    "gtm": [
      "paid-led"
    ],
    "connectors": [
      "meta-ads-api",
      "google-ads-api"
    ]
  },
  "experiment-tracker": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "assisted-demo"
    ],
    "connectors": []
  },
  "jira-workflow-steward": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "assisted-demo"
    ],
    "connectors": []
  },
  "project-shepherd": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "assisted-demo"
    ],
    "connectors": []
  },
  "studio-operations": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "assisted-demo"
    ],
    "connectors": []
  },
  "studio-producer": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "assisted-demo"
    ],
    "connectors": []
  },
  "project-manager-senior": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "500k_1m_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10k_100k_mrr",
      "100k_500k_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "assisted-demo"
    ],
    "connectors": []
  },
  "accounts-payable-agent": {
    "industries": [
      "fintech"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "high-touch-enterprise"
    ],
    "connectors": []
  },
  "agentic-identity-trust": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "agents-orchestrator": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "automation-governance-architect": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "blockchain-security-auditor": {
    "industries": [
      "fintech",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "compliance-auditor": {
    "industries": [
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "corporate-training-designer": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "customer-service": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "data-consolidation-agent": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "government-digital-presales-consultant": {
    "industries": [
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "assisted-demo"
    ],
    "connectors": []
  },
  "healthcare-customer-service": {
    "industries": [
      "healthtech",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "healthcare-marketing-compliance": {
    "industries": [
      "regulated",
      "healthtech"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "hospitality-guest-services": {
    "industries": [
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "hr-onboarding": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "self-serve"
    ],
    "connectors": []
  },
  "identity-graph-operator": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "language-translator": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "legal-billing-time-tracking": {
    "industries": [
      "fintech"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "legal-client-intake": {
    "industries": [
      "saas-b2b",
      "open-source",
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "legal-document-review": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "loan-officer-assistant": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "lsp-index-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "real-estate-buyer-seller": {
    "industries": [
      "marketplace"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "recruitment-specialist": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "0_10k_arr",
      "10k_100k_mrr"
    ],
    "gtm": [],
    "connectors": []
  },
  "report-distribution-agent": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "retail-customer-returns": {
    "industries": [
      "ecommerce-dtc",
      "saas-b2c"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "sales-data-extraction-agent": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "sales-outreach": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "civil-engineer": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "cultural-intelligence-strategist": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "developer-advocate": {
    "industries": [
      "saas-b2b",
      "open-source"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "community-led"
    ],
    "connectors": []
  },
  "document-generator": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "french-consulting-market": {
    "industries": [
      "agency-services"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [
      "assisted-demo"
    ],
    "connectors": []
  },
  "korean-business-navigator": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "mcp-builder": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "model-qa": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "salesforce-architect": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [],
    "connectors": [
      "salesforce"
    ]
  },
  "workflow-architect": {
    "industries": [
      "saas-b2b"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "study-abroad-advisor": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "supply-chain-strategist": {
    "industries": [],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "zk-steward": {
    "industries": [
      "fintech",
      "regulated"
    ],
    "stages": [
      "100k_500k_arr",
      "1m_5m_arr",
      "10k_100k_mrr",
      "500k_1m_arr"
    ],
    "gtm": [],
    "connectors": []
  },
  "executive-brief": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr",
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "referral-led"
    ],
    "connectors": []
  },
  "quickstart": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr",
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "referral-led"
    ],
    "connectors": []
  },
  "nexus-strategy": {
    "industries": [
      "saas-b2b",
      "agency-services"
    ],
    "stages": [
      "1m_5m_arr",
      "5m_10m_arr",
      "10m_plus_arr",
      "10k_100k_mrr",
      "100k_500k_arr",
      "500k_1m_arr"
    ],
    "gtm": [
      "high-touch-enterprise",
      "referral-led"
    ],
    "connectors": []
  }
};
